name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Setup Playwright
      - uses: microsoft/setup-playwright@v2
      - uses: actions/checkout@v4
      - uses: education/autograding@v1
